### ISSUE TITLE
Will the total amount of charge collected be measured at the end of 5 minutes of the competition?

### ISSUE THREAD

**Issue by SachinGoud-24** [romainrossi/make_your_robot_tick#10]
Should the bot reach the storage station only at the end or is it at the liberty of the team?

**Comment by romainrossi** [comment]
The robot is free to reach the Energy Storage Station as often as needed during the match. Is is at the liberty of the team to choose a strategy to be able to collect and deliver as much energy as possible.
The energy counter starts at 0 and is increased each time the robot deliver energy to the ESS. The energy counter will never decrease during the match. The score takes into account the value of the energy counter at the end of the match.
As bonus points are awarded each time the robot connect to a power source or to the ESS, is seems preferable to deliver energy multiple times during the match. However, successive connection to the same item (source or ESS) will only be counted once.
