### ISSUE TITLE
Using another processor as a master to control the SAM board and the MSP 430

### ISSUE THREAD

**Issue by mentalrecessmonkey** [romainrossi/make_your_robot_tick#12]
Are we allowed to use an extra microprocessor in parallel to the SAM board to act as a master and control the whole bot?

**Comment by romainrossi** [comment]
As stated by the section 3.3.1 in the Rule Book:
> All teams have to use the provided (micro-controller) board.
This statement was intended to enforce the constraint that the main processor is the MSP430 on the Launchpad board. Thus, the robot motion and main behavior must be controller by a software running on the MSP430, a very power-efficient micro-controller (the contest is about energy harvesting).

However, you can add any component you want on the additional board you develop (the energy harvesting system). So it is not forbidden to add a CPU of any kind on your add-on board to make processing alongside the MSP430. If you directly connect GPIO of your additional processor to the MSP or the SAMboard; pay attention to the voltage level to avoid destruction.

As an additional information, you can develop the embedded program for the MSP430 using any software toolkit you want : 
- Code Composer Studio for raw C/C++
- Energia or Arduino for a higher-level perspective (see the PlatformIO toolbox)
