### ISSUE TITLE
Insufficient power

### ISSUE THREAD

**Issue by Ganeshvadhri** [romainrossi/make_your_robot_tick#16]
We are using a Power Bank(5v ,1amp) to power the mobile base, but the power is not sufficient for both the motors as well as the sensors we are using . As an alternative we could not use a lipo battery with embedded NTC as it is not available for us. So can you give us some suggestions ?

**Comment by romainrossi** [comment]
I suggest you start by measuring the actual current needed by your system by cutting a USB cord and inserting an Ampere meter on the 5V wire.
Once you have this measure, you can select a power bank with the appropriate output rating.
