### ISSUE TITLE
Tests on game fields

### ISSUE THREAD

**Issue by Ganeshvadhri** [romainrossi/make_your_robot_tick#19]
The white line in the competition might give different IR values to which the IR gives with the white line we use for testing. So will there be time for IR CALIBRATION before the competition?
And are we allowed to test our bot on the platform before the competition ?

**Comment by romainrossi** [comment]
The two game fields will be available for testing during the review of the robots in the morning, which should last for about 1h30. There will be additional testing time during the lunch break. All the teams will have to collaborate to share these time slots.

During the selection and final rounds, the game fields will be used full-time.

I strongly suggest you to develop a quick calibration procedure (<20 seconds), so you can perform and check your sensors calibration during the setup time at the start of each match.

This setup time will be short (1 to 2 minutes), so you need to be efficient.
