### ISSUE TITLE
not clear how bot charges from the charging place

### ISSUE THREAD

**Issue by sanjayav** [romainrossi/make_your_robot_tick#20]
Good morning 
I have a doubt regarding the charging and discharging process by the energy harvesting system 
Should It be a wireless charging and discharging  or else wired charging and discharging ???

**Comment by romainrossi** [comment]
To charge and deliver energy to the Energy Storage System, tour robot can connect using 2 copper contacts placed on each source and the ESS.
The RuleBook describes the size and place of these copper contacts.
