### ISSUE TITLE
bot charging

### ISSUE THREAD

**Issue by sanjayav** [romainrossi/make_your_robot_tick#22]
How does the robot charge when I goes to a position of station any example pics

**Comment by romainrossi** [comment]
I don't have example pictures.

Your robot should charge the embedded energy storage unit by connecting to the two copper contacts rings located on each source and the ESS.
I think using spring-loaded contacts to connect your robot to the devices is the best way.

See the pictures and schematics in the RuleBook : on Figure1, page3, you can see the copper rings wrapped around each source and the ESS in goldish color.
Figure 3 page 4 gives a detailed view of a source, and the associated schematics. Look especially for the height of each contact from the floor as you will need to adjust the height of the contacts on your robot to match.

Other issues giving information about ESS and sources : #3 #4 #5 #6  #8 #10 #14 #18
