### ISSUE TITLE
EMERGENCY BUTTON

### ISSUE THREAD

**Issue by Ganeshvadhri** [romainrossi/make_your_robot_tick#23]
It is mentioned in the rule book that for security reasons all robots must have an emergency button for the robot to come to halt instantly.
So, is it enough if the robot just comes to halt or should the power supply to the microcontroller be cut off?

**Comment by romainrossi** [comment]
As stated in the RuleBook, rhe emergency stop button must stop the robot. If it do that, then it is ok.
You have no obligation to cut the power of the embedded controller or motors, just to halt the robot.
