### ISSUE TITLE
When will the charging stations be powered on?

### ISSUE THREAD

**Issue by SachinGoud-24** [romainrossi/make_your_robot_tick#25]
Will all the charging stations be switched on at once? At the beginning of the competition, and will follow the cycle mentioned in fig.5 of page 5, till the end of 5 minutes of the competition? 

Also how long will the Energy storage station take to measure the charge collected by the bot?

**Comment by romainrossi** [comment]
The sources are activated in each match according to the schedule of the figure 5. So at the beginning of the match, only the two "Slow/Regular" sources are enabled. The schedule of the figure 5 covers the whole duration of the match.

**Comment by romainrossi** [comment]
The energy storage station counts the energy delivered by your robot. It is a 100ohms resistor and the current is measured and integrated to make the score. The more current your robot push in the 100ohms resistor, the faster you score points. In fact, your design will be what set the time to count the energy.

You can find the schematics in the repository, src/elec/ folder (Kicad 5 format)
