### ISSUE TITLE
Regarding Discharging  of the bot 

### ISSUE THREAD

**Issue by Ganeshvadhri** [romainrossi/make_your_robot_tick#26]
If the Bot goes to an electrode which is not active at that time ,then will the energy harvesting circuit of the  robot discharge? 
That is, will the circuit of the charging station break when it is not active?

**Comment by romainrossi** [comment]
Yes, your energy storage system will discharge (slightly) if you connect it to a source which is not active. The discharge will be through the 470ohm resistor and led, so the current will be small.

As you have the complete schedule of the sources activations, I suggest you try to avoid this situation. You can also use the embedded ADC in the MSP430 to sense the activation of the source. You can also insert a diode in series to prevent discharge (you will the need to bypass it using eg a relay to deliver energy to the ESS).
